version: "3.8"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  api: &backend
    build:
      dockerfile: docker/Dockerfile.api
      context: .
    image: 573620237252.dkr.ecr.us-west-2.amazonaws.com/inobus/api
  rabbitmq:
    build:
      dockerfile: ../Dockerfile.rabbitmq
      context: docker/rabbitmq/
    image: 573620237252.dkr.ecr.us-west-2.amazonaws.com/inobus/rabbitmq
    ports:
      - 15672:15672 # For management
      - 5672:5672 # For AMQP
      - 18820:18820 # For MQTT
  consumer:
    <<: *backend
    command: sh -c "./prestart.sh && python main_consumer.py"
