version: "3.8"

services:
  mongodb:
    extends:
      file: common.yaml
      service: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin1234!
      - MONGO_INITDB_DATABASE=next_generation
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - app
  api:
    extends:
      file: common.yaml
      service: api
    env_file:
      - .env.example
    environment:
      - DB_URL=mongodb://mongodb:27017/
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - "80:80"
    networks:
      - app
    volumes:
      - .:/app
    command: "/start-reload.sh"
  rabbitmq:
    extends:
      file: common.yaml
      service: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin1234!
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mongodb:
